### ISSUE TITLE
active/active HA leads to bad-state PV

### ISSUE THREAD

**Issue by childsb** [pmorie/pv-haxxz#2]
At the design meetup the idea was floated that there's an initial write to PVC "claiming" it before the write to PV which we didn't implement in the pseudocode. (The 'provisional bind' as suggested by Daniel)

One benefit of writing the PVC, then the PV and finally the PV again was it ensured only one PV was claimed on behalf of a PVC.  Without that first write (and other controllers failing this write and aborting the bind) in an active/active controller situation two PVs could map to one PVC.

I believe we'll want the provisional bind if we support active/active instead of rolling back a duplicate-claimed PV.

**Comment by pmorie** [comment]
@childsb @swagiaal @jsafrane @rootfs @saad-ali @thockin let's clear this one out, PTAL and we'll discuss

**Comment by ghost** [comment]
> Without that first write (and other controllers failing this write and aborting the bind) in an active/active controller situation two PVs could map to one PVC.

I don't think this can happen. The pointer has to be written in both directions for the binding to be considered complete, and only one of the two controllers will win that race. The issue is however that you will end up with a pv which points to a claim which does not point back. This issue will be handled here: https://github.com/pmorie/pv-haxxz/blob/master/controller.go#L359

When we do active-active HA, if we see that the above clean up is a bottle neck then we can explore writing to the claim first to remove it from the pool and reduce collisions.

**Comment by thockin** [comment]
agree
