### ISSUE TITLE
Should we reset UID on rollback?

### ISSUE THREAD

**Issue by jsafrane** [pmorie/pv-haxxz#5]
In case that two controllers bind two PVs to a PVC, only one PV 'wins' and we roll back all changes done by the controller to the other PV. See https://github.com/pmorie/pv-haxxz/blob/master/controller.go#L357

Now the question is - if the 'loosing' PV is pre-bound by user, should we clear its `.pv.Spec.ClaimRef.UID`? Current code does not do so: https://github.com/pmorie/pv-haxxz/blob/master/controller.go#L374. We know that user set `pv.Spec.ClaimRef.Name/Namespace`, we do not know who set `pv.Spec.ClaimRef.UID`. Do we need another annotation for that? `UIDBoundByController`?

The same situation will happen when we recycle PVs and make them Available again. If the PV was pre-bound by user, we won't touch its `pv.Spec.ClaimRef.Name/Namspace`. Should we clear its `pv.Spec.ClaimRef.UID` or not?

@pmorie @thockin @saad-ali @swagiaal @childsb @rootfs

**Comment by jsafrane** [comment]
Answering myself, we **must** clear `pv.Spec.ClaimRef.UID` on rollback or on successful recycle.  Users cannot submit volumes pre-bound to a claim with `pv.Spec.ClaimRef.UID` set - they are indistinguishable from volume that needs recycling.

See https://github.com/pmorie/pv-haxxz/blob/master/controller.go#L269

**Comment by thockin** [comment]
If this is true we should enforce this in validation and reject those
operations

**Comment by saad-ali** [comment]
> Users cannot submit volumes pre-bound to a claim with pv.Spec.ClaimRef.UID set - they are indistinguishable from volume that needs recycling

We are [telling customers today](https://github.com/kubernetes/kubernetes/issues/21498#issuecomment-208613438) that if they want to prebind a PV to PVC that doesn't exist yet, create the PV with a claimRef including the namespace, name, **and UID**. Then create a PVC with the same namespace, name, and uid. It would be nice if we could keep the same behavior in the future so that we don't break these users. But looks like that may be unavoidable.

**Comment by thockin** [comment]
Users don't get to choose their own UID, so they CAN NOT pre-bind by UID.

**Comment by saad-ali** [comment]
You're right, disregard my comment.
